version: "3"

services:
  
  api:
    build:
      context: ./docker/api/
    container_name: ${PROJECT_NAME}-api
    volumes:
      - ./api:${API_DIRECTORY}
    networks:
      - ${PROJECT_NAME}

  frontend:
    build: ./frontend
    container_name: ${PROJECT_NAME}-frontend
    networks:
      skillup:
        ipv4_address: ${FRONTEND_IPV4}

  nginx:
    build:
      context: ./docker/nginx
    container_name: ${PROJECT_NAME}-nginx
    volumes:
      - ./api:${API_DIRECTORY}
      - ./frontend:${FRONTEND_DIRECTORY}
    depends_on:
      - api
    environment:
      FRONTEND_DIRECTORY: ${FRONTEND_DIRECTORY}
      API_DIRECTORY: ${API_DIRECTORY}
    networks:
      skillup:
        ipv4_address: ${NGINX_IPV4}


volumes:
  api:
  nginx:
  data:

networks:
  skillup:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/16
