app:
  resource: '../src/Controller/'
  type: annotation
api_login:
  path: /api/login
confirm_registration:
  path: /api/confirm-registration/{token}
  controller: App\Controller\RegistrationController::confirmRegistration
